apiVersion: v1
kind: Service
metadata:
  name: colorapp-service
  labels:
    app: colorapp
    type: frontend
spec:
  type: NodePort
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    type: frontend
