apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: front-end 
spec:
  replicas: 3
  template:
    metadata:
      labels:
       type: front-end
    spec:
      containers:
      - name: my-nginx
        image: nginx
   selector:
     matchLabel:
       type: front-end
