apiVersion: v1
kind: ReplicationController
metadata:
  name: GangaReplicaSet
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
	metadata:
	  name: my-app
	  labels:
	    app: myapp
	    type: front-end
	spec:
	  containers:
	  - name: nginx-container
	    image: nginx